services:
  mongodb:
    image: mongo:7.0.5
    container_name: mongodb
    ports:
      - "27019:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: biteup
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
